<program> ::= 
			<identifier> ":" <block> ENDP <identifier> "."

<block> ::= 
			DECLARATION <declaration_block> CODE <statment_list>
			| CODE <statment_list>


<declaration_identifier> ::= 
			<identifier> 
			| <identifier> "," <declaration_identifier>

<declaration_block> ::= 
			<declaration_identifier> OF TYPE <type> ";" 
			| <declaration_identifier> OF TYPE <type> ";" <declaration_block>

<type> ::= 
			CHARACTER 
			| INTEGER 
			| REAL

<statement_list> ::= 
			<statement> 
			| <statement> ";" <statement_list>

<statement> ::= 
			<assignment_statment> 
			| <if_statement> 
			| <do_statement> 
			| <while_statement> 
			| <for_statement> 
			| <write_statement> 
			| <read_statement> 

<assignment_statment> ::= 
			<expression> "->" <identifier>

<if_statement> ::= 
			IF <conditional> THEN <statement_list> ENDIF
            | IF <conditional> THEN <statement_list> ELSE <statement_list> ENDIF

<do_statement> ::= 
			DO <statement_list> WHILE <conditional> ENDDO

<while_statement> ::= 
			WHILE <conditional> DO <statement_list> ENDWHILE

<for_statement> ::= 
			FOR <identifier> IS <expression> BY <expression> TO <expression> DO <expression> ENDFOR

<write_statement> ::= 
			NEWLINE 
			| WRITE "("<output_list>")" 

<read_statement> ::= 
			READ "("<identifier>")"

<output_list> ::= 
			<value> 
			| <value> "," <output_list>


<conditional> ::= 
			<conditional_body>
			| <not_expression> <conditional_body> 
			| <expression> <comparator> <expression> AND <conditional> 
			|<expression> <comparator> <expression> OR <conditional>

<conditional_body> ::= 
			<expression> <comparator> <expression>

<not_expression> ::=
			NOT
			| NOT <not_expression>
			
<comparator> ::= 
			"="
			|"<>"
			|"<"
			|">"
			|"<="
			|">="
				
<expression> ::= 
			<term> 
			| <term> "+" <expression> 
			| <term> "-" <expression>

<term> ::= 
			<value> 
			| <value> "*" <term>
			| <value> "/" <term>

<value> ::= 
			<identifier> 
			| <constant> 
			| "("<expression>")"
			
<constant> ::= 
			<number_constant> 
			| <character_constant>

<character_constant> ::= 
			"'" <character> "'"

<number_constant> ::= 
			"-" <any_digit> "." <any_digit>
			| <any_digit> "." <any_digit>
			| "-" <any_digit>
			| <any_digit>

<identifier> ::= 
			<character> <identifier_member>

<identifier_member> ::= 
			<any_character> 
			| <any_character> <identifier_member> 
			|<any_digit> 
			|<any_digit> <identifier_member>

<any_digit> ::= 
			<digit> 
			| <digit> <any_digit>
			
<any_character> ::= 
			<character><any_character>

<character> ::= 
			"a"| "b"| "c"| "d"| "e"| "f"| "g"| "h"| "i"| "j"| "k"| "l"| "m"| "n"| "o"| "p"| "q"| "r"| "s"| "t"| "u"| "v"| "w"| "x"| "y"| "z" |
			"A"| "B"| "C"| "D"| "E"| "F"| "G"| "H"| "I"| "J"| "K"| "L"| "M"| "N"| "O"| "P"| "Q"| "R"| "S"| "T"| "U"| "V"| "W"| "X"| "Y"| "Z"
			
<digit> ::= 
			0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 